<div id="inner_banner" class="section inner_banner_section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="title-holder">
            <div class="title-holder-cell text-left">
              <h1 class="page-title">404 Error</h1>
              <ol class="breadcrumb">
                <li><a href="<?=App::config('url')?>index/home">Home</a></li>
                <li class="active">404 Error</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section padding_layout_1">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="center margin_bottom_30_all"> <img class="margin_bottom_30_all" src="<?=App::config('url')?>public/images/services/404_error_img.png" alt="#"> </div>
        <div class="heading text_align_center">
          <h2>OOOPS, THIS PAGE COULD NOT BE FOUND!</h2>
        </div>
        <div class="center"> <a class="btn sqaure_bt light_theme_bt" href="<?=App::config('url')?>index/home">Back Home</a> </div>
      </div>
    </div>
  </div>
</div>