<div id="inner_banner" class="section inner_banner_section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="title-holder">
            <div class="title-holder-cell text-left">
              <h1 class="page-title">Our Pricing</h1>
              <ol class="breadcrumb">
                <li><a href="<?=App::config('url')?>index/home">Home</a></li>
                <li class="active">Pricing</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section padding_layout_1 service_list">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="main_heading text_align_center">
            <h2>Our Pricing Plans</h2>
          </div>
        </div>
      </div>
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="price_table row" style="margin-top: 0;">
          <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="price_table_inner margin_bottom_30">
              <div class="price_head text_align_center">
                <h5>Starter</h5>
                <p>The best to start</p>
              </div>
              <div class="price_contant">
                <div class="center">
                  <p class="price_amount">$ <span class="price_no">180</span>/Per Month</p>
                </div>
                <div class="price_cont text_align_center">
                  <p>Fast service</p>
                  <p>Safe payments</p>
                  <p>Fully trained employees</p>
                  <p>Sustainable products</p>
                </div>
              </div>
              <div class="price_bottom">
                <div class="center"> <a href="#" class="btn dark_gray_bt">Get Started</a> </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 price_table_active">
            <div class="row">
              <div class="price_table_inner margin_bottom_30">
                <div class="price_head text_align_center white_fonts">
                  <h5>Professional</h5>
                  <p>The best to start</p>
                </div>
                <div class="price_contant">
                  <div class="center">
                    <p class="price_amount">$ <span class="price_no">210</span>/Per Month</p>
                  </div>
                  <div class="price_cont text_align_center">
                    <p>Fast service</p>
                    <p>Safe payments</p>
                    <p>Fully trained employees</p>
                    <p>Sustainable products</p>
                  </div>
                </div>
                <div class="price_bottom">
                  <div class="center"> <a href="#" class="btn main_bt">Get Started</a> </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="price_table_inner">
              <div class="price_head text_align_center">
                <h5>Business</h5>
                <p>The best to start</p>
              </div>
              <div class="price_contant">
                <div class="center">
                  <p class="price_amount">$ <span class="price_no">240</span>/Per Month</p>
                </div>
                <div class="price_cont text_align_center">
                  <p>Fast service</p>
                  <p>Safe payments</p>
                  <p>Fully trained employees</p>
                  <p>Sustainable products</p>
                </div>
              </div>
              <div class="price_bottom">
                <div class="center"> <a href="#" class="btn dark_gray_bt">Get Started</a> </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section padding_layout_1 testmonial_section white_fonts">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="main_heading text_align_left">
            <h2 style="text-transform: none;">What Clients Say?</h2>
            <p class="large">Here are testimonials from clients..</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-7">
        <div class="full">
          <div id="testimonial_slider" class="carousel slide" data-ride="carousel">
            <ul class="carousel-indicators">
              <li data-target="#testimonial_slider" data-slide-to="0" class="active"></li>
              <li data-target="#testimonial_slider" data-slide-to="1"></li>
              <li data-target="#testimonial_slider" data-slide-to="2"></li>
            </ul>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <div class="testimonial-container">
                  <div class="testimonial-content"> You guys rock! I was pleasantly surprised that they did the repair of my computer in a very short time. </div>
                  <div class="testimonial-photo"> <img src="<?=App::config('url')?>public/images/services/client1.jpg" class="img-responsive" alt="#" width="150" height="150"> </div>
                  <div class="testimonial-meta">
                    <h4>Elon Musk</h4>
                    <span class="testimonial-position">CEO of SpaceX</span> </div>
                </div>
              </div>
              <div class="carousel-item">
                <div class="testimonial-container">
                  <div class="testimonial-content">Thank you for making it painless, pleasant and most of all hassle free! I wish I would have thought of it first. 
                    I am really satisfied with my first laptop service. </div>
                  <div class="testimonial-photo"> <img src="<?=App::config('url')?>public/images/services/client2.jpg" class="img-responsive" alt="#" width="150" height="150"> </div>
                  <div class="testimonial-meta">
                    <h4>Jeff Bezos</h4>
                    <span class="testimonial-position">American entrepreneur</span> </div>
                </div>
              </div>
              <div class="carousel-item">
                <div class="testimonial-container">
                  <div class="testimonial-content"> You guys are great! Fast delivery of services. I ordered 50 games that arrived to me within 2 days, very fast delivery. Thank you guys a lot. </div>
                  <div class="testimonial-photo"> <img src="<?=App::config('url')?>public/images/services/client3.jpg" class="img-responsive" alt="#" width="150" height="150"> </div>
                  <div class="testimonial-meta">
                    <h4>Mate Rimac</h4>
                    <span class="testimonial-position">Croatian innovator</span> </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-5">
        <div class="full"> </div>
      </div>
    </div>
  </div>
</div>
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="contact_us_section">
            <div class="call_icon"> <img src="<?=App::config('url')?>public/images/services/phone_icon.png" alt="#" /> </div>
            <div class="inner_cont">
              <h2>REQUEST A FREE QUOTE</h2>
              <p>Get answers and advice from people you want it from.</p>
            </div>
            <div class="button_Section_cont"> <a class="btn dark_gray_bt" href="<?=App::config('url')?>index/contact">Contact us</a> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section padding_layout_1" style="padding: 50px 0;">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
      </div>
    </div>
  </div>
</div>