<div id="inner_banner" class="section inner_banner_section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="title-holder">
            <div class="title-holder-cell text-left">
              <h1 class="page-title">Blog Detail</h1>
              <ol class="breadcrumb">
                <li><a href="<?=App::config('url')?>index/home">Home</a></li>
                <li><a href="<?=App::config('url')?>blog/index">Blog List</a></li>
                <li class="active">Blog Detail</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section padding_layout_1 blog_grid">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 pull-right">
        <div class="full">
          <div class="blog_section margin_bottom_0">
            <div class="blog_feature_cantant">
              <p class="blog_head"><?=$blog->title?></p>
              <p><?=$blog->text?></p>
              <div class="post_info">
                <ul>
                  <li><i class="fa fa-user" aria-hidden="true"></i> <?php $author = Blog::findAuthor($blog->id); echo $author;?></li>
                  <li><i class="fa fa-calendar" aria-hidden="true"></i> <?=$blog->blogdate?></li>
                </ul>
              </div>
            </div>
              <?php if($blog->image !=null): ?>
              <div class="blog_feature_img"> <img class="img-responsiveBlogDetail" src="<?=App::config('url')?>public/images/blog/<?=$blog->image?>" alt="#"> </div>
            <?php endif;?>
            <div class="comment_section">            
            </div>
            <div class="view_commant">
              <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">
                </div>
                <div class="col-lg-12 col-md-10 col-sm-9 col-xs-12">
                <?php if($comment != null && !isset($_SESSION['authorized'])): ?>
                <?php foreach($comment as $com): ?>
                  <div class="full theme_bg white_fonts command_cont">
                    <p class="comm_head">
                      <?=$com->writer?><span><?=$com->date?></span>
                  </p>
                    <p> <?=$com->comment?></p>
                  </div>
                  <?php endforeach; ?>
                  <?php include 'pagingCom.phtml'; ?>
                  <?php elseif($comment != null && isset($_SESSION['authorized'])): ?>
                    <?php foreach($comment as $com): ?>
                  <div class="full theme_bg white_fonts command_cont">
                    <p class="comm_head">
                      <?=$com->writer?><span><?=$com->date?></span>
                    <?php if(Blog::myComment($com->id,$userId)): ?>
                    <a class="rply" href="<?=App::config('url')?>blog/delete_comment?comment=<?=$com->id?>&uid=<?=$userId?>"><i class="fa fa-trash" aria-hidden="true"></i></a>
                    <a class="rply" style="margin-right:10px;" href="<?=App::config('url')?>blog/update_comment?comment=<?=$com->id?>"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                    <?php endif; ?>
                  </p>
                    <p> <?=$com->comment?></p>
                  </div>
                  <?php endforeach; ?>
                  <?php include 'pagingCom.phtml'; ?>
                  <?php else :?>
                    <div class="full theme_bg white_fonts command_cont">
                      <h3>This post has no comments yet.</h3>
                  </div>
                  <?php endif;?>
                </div>
              </div>
            </div>
            <?php if(Request::isAuthorized()): ?>
            <div class="post_commt_form">
              <h4>POST YOUR COMMENT</h4>
              <div class="form_section">
                <form class="form_contant" method="POST" action="<?=App::config('url')?>blog/request">
                  <fieldset class="row">
                  <div class="field col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <textarea class="field_custom" name="comment" placeholder="Comment" required></textarea>
                    <input type="hidden" name="postId" value="<?=$blog->id?>">
                    <input type="hidden" name="writer" value="<?php echo $_SESSION['authorized']->id;?>">
                  </div>
                  <div class="center">
                    <button class="btn main_bt" type="submit">POST COMMENT</button>
                  </div>
                  </fieldset>
                </form>
              </div>
            </div>
            <?php else: ?>
              <div class="post_commt_form">
                <h4 class="text-center">You must be logged in to comment.</h4>
                <a href="<?=App::config('url')?>index/login" class="btn main_bt center" type="submit">Log In</a>
              </div>
              <?php endif;?>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pull-left">
        <div class="side_bar">
          <div class="side_bar_blog">
          <h4>SEARCH</h4>
            <div class="side_bar_search">
              <form action="<?=App::config('url')?>blog/request_blog">
              <div class="input-group stylish-input-group">
                <input class="form-control" name="search" value="<?=$search?>" placeholder="Search" type="text">
                <span class="input-group-addon">
                <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                </span> </div>
              </form>
            </div>
          </div>
          <div class="side_bar_blog">
          <h4><?=strtoupper($random->title)?></h4>
            <p><?=$random->smalldesc?></p>
            <a class="btn sqaure_bt" href="<?=App::config('url')?>services/service_detail?id=<?=$random->id?>">View Service</a>
          </div>
          <div class="side_bar_blog">
            <h4>RECENT POST</h4>
            <div class="recent_post">
              <ul>
                <?php foreach($latestBlog as $lb): ?>
                <li>
                  <p class="post_head"><a href="<?=App::config('url')?>blog/blog_detail?id=<?=$lb->id?>"><?=$lb->title?></a></p>
                  <p class="post_date"><i class="fa fa-calendar" aria-hidden="true"></i> <?=$lb->blogdate?></p>
                </li>
                <?php endforeach; ?>
              </ul>
            </div>
          </div>
          <div class="side_bar_blog">
            <h4>OUR SERVICE</h4>
            <div class="categary">
              <ul>
                <?php foreach($sideService as $sideService): ?>
                <li><a href="<?=App::config('url')?>services/service_detail?id=<?=$sideService->id?>"><i class="fa fa-angle-right"></i> <?=$sideService->title?></a></li>
                <?php endforeach;?>
              </ul>
            </div>
          </div>
          <div class="side_bar_blog">
            <h4>RECENT NEWS</h4>
            <div class="categary">
              <ul>
              <?php foreach($sideNews as $sideNews): ?>
                <li><a href="<?=App::config('url')?>news/news_detail?id=<?=$sideNews->id?>"><i class="fa fa-angle-right"></i> <?=$sideNews->headline?></a></li>
              <?php endforeach;?>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>