<div class="section padding_layout_1 blog_grid">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 pull-right">
        <div class="full">
          <div class="blog_section margin_bottom_0">
            <div class="blog_feature_cantant">
              <p class="blog_head"><?=$blog->title?></p>
              <div class="post_info">
                <ul>
                <li><i class="fa fa-user" aria-hidden="true"></i> <?php $id = Blog::findAuthor($blog->id); echo $id;?></li>
                  <li><i class="fa fa-calendar" aria-hidden="true"></i> <?=$blog->blogdate?></li>
                </ul>
              </div>
              <p><?=$blog->text?></p>
            <?php if($blog->image !=null): ?>
              <div class="blog_feature_img"> <img class="img-responsiveBlogDetail" src="<?=App::config('url')?>public/images/blog/<?=$blog->image?>" alt="#"> </div>
            <?php endif;?>
            <div class="bottom_info margin_bottom_30_all">
              <div class="pull-right">
                <div class="shr">Share: </div>
                <div class="social_icon">
                  <ul>
                    <li class="fb"><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li class="twi"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li class="gp"><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                    <li class="pint"><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="comment_section">
            </div>
            <div class="view_commant">
              <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">
                  <div class="full"> <img class="img-responsive" style="max-width:100px" src="<?=App::config('url')?>public/images/services/client1.png" alt="#"> </div>
                </div>
                <div class="col-lg-10 col-md-10 col-sm-9 col-xs-12">
                  <div class="full theme_bg white_fonts command_cont">
                    <p class="comm_head">Christian Perez <span>April 27,2018</span><a class="rply" href="it_blog_detail.html">Reply</a></p>
                    <p>magine you are 10 years into the future but this time it’s different. Why? Because starting today you actually 
                      begin making changes in your life. Specific intentional changes are not easy. They are intentional because these 
                      changes are changes that you are choosing and they are the changes that will cause you to live the life you want 
                      to live and dream. </p>
                  </div>
                  <div class="full">
                    <div class="row">
                      <div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">
                        <div class="full"> <img class="img-responsive" style="max-width:100px" src="<?=App::config('url')?>public/images/services/client2.png" alt="#"> </div>
                      </div>
                      <div class="col-lg-10 col-md-10 col-sm-9 col-xs-12">
                        <div class="full command_cont margin_bottom_0">
                          <p class="comm_head">Christian Perez <span>April 27,2018</span><a class="rply" href="it_blog_detail.html">Reply</a></p>
                          <p>magine you are 10 years into the future but this time it’s different. Why? Because starting today you actually 
                            begin making changes in your life. Specific intentional changes are not easy. They are 
                            intentional because these changes are changes. </p>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">
                        <div class="full"> <img class="img-responsive" style="max-width:100px" src="<?=App::config('url')?>public/images/services/client3.png" alt="#"> </div>
                      </div>
                      <div class="col-lg-10 col-md-10 col-sm-9 col-xs-12">
                        <div class="full command_cont">
                          <p class="comm_head">Christian Perez <span>April 27,2018</span><a class="rply" href="it_blog_detail.html">Reply</a></p>
                          <p>magine you are 10 years into the future but this time it’s different. Why? Because starting today you actually 
                            begin making changes in your life. Specific intentional changes are not easy. They are 
                            intentional because these changes are changes. </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">
                  <div class="full"> <img class="img-responsive" style="max-width:100px" src="<?=App::config('url')?>public/images/services/client1.png" alt="#"> </div>
                </div>
                <div class="col-lg-10 col-md-10 col-sm-9 col-xs-12">
                  <div class="full theme_bg white_fonts command_cont">
                    <p class="comm_head">Christian Perez <span>Sep 27,2017</span><a class="rply" href="it_blog_detail.html">Reply</a></p>
                    <p>magine you are 10 years into the future but this time it’s different. Why? Because starting today you actually 
                      begin making changes in your life. Specific intentional changes are not easy. They are intentional because these 
                      changes are changes that you are choosing and they are the changes that will cause you to live the life you want 
                      to live and dream. </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="post_commt_form">
              <h4>POST YOUR COMMENT</h4>
              <div class="form_section">
                <form class="form_contant" action="index.html">
                  <fieldset class="row">
                  <div class="field col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <input class="field_custom" placeholder="Email" type="email" required>
                  </div>
                  <div class="field col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <input class="field_custom" placeholder="Phone" type="text" required>
                  </div>
                  <div class="field col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <input class="field_custom" placeholder="Password" type="password" required>
                  </div>
                  <div class="field col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <textarea class="field_custom" placeholder="Comment" required></textarea>
                  </div>
                  <div class="center">
                    <button class="btn main_bt">SUBMIT NOW</button>
                  </div>
                  </fieldset>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pull-left">
        <div class="side_bar">
          <div class="side_bar_blog">
            <h4>SEARCH</h4>
            <div class="side_bar_search">
              <div class="input-group stylish-input-group">
                <input class="form-control" placeholder="Search" type="text">
                <span class="input-group-addon">
                <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                </span> </div>
            </div>
          </div>
          <div class="side_bar_blog">
            <h4>ABOUT AUTHOR</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. sed do eiusmod tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
          <div class="side_bar_blog">
            <h4>RECENT POST</h4>
            <div class="recent_post">
              <ul>
                <li>
                  <p class="post_head"><a href="#">How To Look Up</a></p>
                  <p class="post_date"><i class="fa fa-calendar" aria-hidden="true"></i> Aug 20, 2017</p>
                </li>
                <li>
                  <p class="post_head"><a href="#">Compatible Inkjet Cartridge</a></p>
                  <p class="post_date"><i class="fa fa-calendar" aria-hidden="true"></i> Aug 20, 2017</p>
                </li>
                <li>
                  <p class="post_head"><a href="#">Treat That Oral Thrush Now</a></p>
                  <p class="post_date"><i class="fa fa-calendar" aria-hidden="true"></i> Aug 20, 2017</p>
                </li>
              </ul>
            </div>
          </div>
          <div class="side_bar_blog">
            <h4>CATEGORIES</h4>
            <div class="categary">
              <ul>
                <li><a href="#"><i class="fa fa-caret-right"></i> Change Oil and Filter</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> Brake Pads Replacement</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> Timing Belt Replacement</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> Pre-purchase Car Inspection</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> Starter Replacement</a></li>
              </ul>
            </div>
          </div>
          <div class="side_bar_blog">
            <h4>TAG</h4>
            <div class="tags">
              <ul>
                <li><a href="#">Bootstrap</a></li>
                <li><a href="#">HTML5</a></li>
                <li><a href="#">Wordpress</a></li>
                <li><a href="#">Bootstrap</a></li>
                <li><a href="#">HTML5</a></li>
              </ul>
            </div>
          </div>
          <div class="side_bar_blog">
            <h4>CATEGORIES</h4>
            <div class="categary">
              <ul>
                <li><a href="#"><i class="fa fa-caret-right"></i> June (12)</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> January (12)</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> March (12)</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> November (12)</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> December (12)</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section padding_layout_1 testmonial_section white_fonts">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="main_heading text_align_left">
            <h2 style="text-transform: none;">What Clients Say?</h2>
            <p class="large">Here are testimonials from clients..</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-7">
        <div class="full">
          <div id="testimonial_slider" class="carousel slide" data-ride="carousel">
            <ul class="carousel-indicators">
              <li data-target="#testimonial_slider" data-slide-to="0" class="active"></li>
              <li data-target="#testimonial_slider" data-slide-to="1"></li>
              <li data-target="#testimonial_slider" data-slide-to="2"></li>
            </ul>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <div class="testimonial-container">
                  <div class="testimonial-content"> You guys rock! I was pleasantly surprised that they did the repair of my computer in a very short time. </div>
                  <div class="testimonial-photo"> <img src="<?=App::config('url')?>public/images/services/client1.jpg" class="img-responsive" alt="#" width="150" height="150"> </div>
                  <div class="testimonial-meta">
                    <h4>Elon Musk</h4>
                    <span class="testimonial-position">CEO of SpaceX</span> </div>
                </div>
              </div>
              <div class="carousel-item">
                <div class="testimonial-container">
                  <div class="testimonial-content">Thank you for making it painless, pleasant and most of all hassle free! I wish I would have thought of it first. 
                    I am really satisfied with my first laptop service. </div>
                  <div class="testimonial-photo"> <img src="<?=App::config('url')?>public/images/services/client2.jpg" class="img-responsive" alt="#" width="150" height="150"> </div>
                  <div class="testimonial-meta">
                    <h4>Jeff Bezos</h4>
                    <span class="testimonial-position">American entrepreneur</span> </div>
                </div>
              </div>
              <div class="carousel-item">
                <div class="testimonial-container">
                  <div class="testimonial-content"> You guys are great! Fast delivery of services. I ordered 50 games that arrived to me within 2 days, very fast delivery. Thank you guys a lot. </div>
                  <div class="testimonial-photo"> <img src="<?=App::config('url')?>public/images/services/client3.jpg" class="img-responsive" alt="#" width="150" height="150"> </div>
                  <div class="testimonial-meta">
                    <h4>Mate Rimac</h4>
                    <span class="testimonial-position">Croatian innovator</span> </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-5">
        <div class="full"> </div>
      </div>
    </div>
  </div>
</div>
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="contact_us_section">
            <div class="call_icon"> <img src="<?=App::config('url')?>public/images/services/phone_icon.png" alt="#" /> </div>
            <div class="inner_cont">
              <h2>REQUEST A FREE QUOTE</h2>
              <p>Get answers and advice from people you want it from.</p>
            </div>
            <div class="button_Section_cont"> <a class="btn dark_gray_bt" href="<?=App::config('url')?>index/contact">Contact us</a> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section padding_layout_1" style="padding: 50px 0;">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
      </div>
    </div>
  </div>
</div>