<div class="section padding_layout_1 blog_grid">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 pull-right">
        <div class="full">
          <div class="blog_section margin_bottom_0">
            <div class="blog_feature_cantant">
              <p class="blog_head"><?=$blog->title?></p>
              <p><?=$blog->text?></p>
              <div class="post_info">
                <ul>
                  <li><i class="fa fa-user" aria-hidden="true"></i> <?php $author = Blog::findAuthor($blog->id); echo $author;?></li>
                  <li><i class="fa fa-calendar" aria-hidden="true"></i> <?=$blog->blogdate?></li>
                </ul>
              </div>
            </div>
              <?php if($blog->image !=null): ?>
              <div class="blog_feature_img"> <img class="img-responsiveBlogDetail" src="<?=App::config('url')?>public/images/blog/<?=$blog->image?>" alt="#"> </div>
            <?php endif;?>
            <div class="comment_section">            
            </div>
            <div class="view_commant">
              <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">
                </div>
                <div class="col-lg-12 col-md-10 col-sm-9 col-xs-12">
                <?php if($comment != null): ?>
                <?php foreach($comment as $com): ?>
                  <div class="full theme_bg white_fonts command_cont">
                    <p class="comm_head"><?=$com->writer?><span><?=$com->date?></span><a class="rply" href="it_blog_detail.html">Reply</a></p>
                    <p>magine you are 10 years into the future but this time it’s different. Why? Because starting today you actually 
                      begin making changes in your life. Specific intentional changes are not easy. They are intentional because these 
                      changes are changes that you are choosing and they are the changes that will cause you to live the life you want 
                      to live and dream. </p>
                  </div>
                  <?php endforeach; ?>
                  <?php else :?>
                    <div class="full theme_bg white_fonts command_cont">
                      <h3>This post has no comments yet.</h3>
                  </div>
                  <?php endif;?>
                </div>
              </div>
            </div>
            <div class="post_commt_form">
              <h4>POST YOUR COMMENT</h4>
              <div class="form_section">
                <form class="form_contant" action="index.html">
                  <fieldset class="row">
                  <div class="field col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <input class="field_custom" placeholder="Email" type="email" required>
                  </div>
                  <div class="field col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <input class="field_custom" placeholder="Phone" type="text" required>
                  </div>
                  <div class="field col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <input class="field_custom" placeholder="Password" type="password" required>
                  </div>
                  <div class="field col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <textarea class="field_custom" placeholder="Comment" required></textarea>
                  </div>
                  <div class="center">
                    <button class="btn main_bt">SUBMIT NOW</button>
                  </div>
                  </fieldset>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pull-left">
        <div class="side_bar">
          <div class="side_bar_blog">
          <h4>SEARCH</h4>
            <div class="side_bar_search">
              <form action="<?=App::config('url')?>news/request_blog">
              <div class="input-group stylish-input-group">
                <input class="form-control" name="search" value="<?=$search?>" placeholder="Search" type="text">
                <span class="input-group-addon">
                <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                </span> </div>
              </form>
            </div>
          </div>
          <div class="side_bar_blog">
          <h4><?=strtoupper($random->title)?></h4>
            <p><?=$random->smalldesc?></p>
            <a class="btn sqaure_bt" href="<?=App::config('url')?>services/service_detail?id=<?=$random->id?>">View Service</a>
          </div>
          <div class="side_bar_blog">
            <h4>RECENT POST</h4>
            <div class="recent_post">
              <ul>
                <?php foreach($latestBlog as $lb): ?>
                <li>
                  <p class="post_head"><a href="<?=App::config('url')?>blog/blog_detail?id=<?=$lb->id?>"><?=$lb->title?></a></p>
                  <p class="post_date"><i class="fa fa-calendar" aria-hidden="true"></i> <?=$lb->blogdate?></p>
                </li>
                <?php endforeach; ?>
              </ul>
            </div>
          </div>
          <div class="side_bar_blog">
            <h4>CATEGORIES</h4>
            <div class="categary">
              <ul>
                <li><a href="#"><i class="fa fa-caret-right"></i> Change Oil and Filter</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> Brake Pads Replacement</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> Timing Belt Replacement</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> Pre-purchase Car Inspection</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> Starter Replacement</a></li>
              </ul>
            </div>
          </div>
          <div class="side_bar_blog">
            <h4>TAG</h4>
            <div class="tags">
              <ul>
                <li><a href="#">Bootstrap</a></li>
                <li><a href="#">HTML5</a></li>
                <li><a href="#">Wordpress</a></li>
                <li><a href="#">Bootstrap</a></li>
                <li><a href="#">HTML5</a></li>
              </ul>
            </div>
          </div>
          <div class="side_bar_blog">
            <h4>CATEGORIES</h4>
            <div class="categary">
              <ul>
                <li><a href="#"><i class="fa fa-caret-right"></i> June (12)</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> January (12)</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> March (12)</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> November (12)</a></li>
                <li><a href="#"><i class="fa fa-caret-right"></i> December (12)</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>