<div id="inner_banner" class="section inner_banner_section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="title-holder">
            <div class="title-holder-cell text-left">
              <h1 class="page-title">News Detail</h1>
              <ol class="breadcrumb">
                <li><a href="<?=App::config('url')?>index/home">Home</a></li>
                <li><a href="<?=App::config('url')?>news/index">News</a></li>
                <li class="active">News Detail</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section padding_layout_1 service_list">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="row">
          <div class="col-md-12 service_blog margin_bottom_50">
            <div class="full">
              <div class="service_img"> <img class="img-responsive" src="<?=App::config('url')?>public/images/news/<?=$news->image?>" alt="#" /> </div>
              <div class="service_cont">
                <h3 class="service_head"><?=$news->headline?></h3>
                <p><?=$news->text?></p>
                <p>Author: <?php $id = News::findAuthor($news->id); echo $id;?></p>
                <p><?=$news->publishDate?></p>
                <hr>
                <h2 style="margin-top: 50px;">Latest News</h2>
              </div>
            </div>
          </div>
          <?php foreach($newNews as $nn): ?>
          <div class="col-md-6 service_blog margin_bottom_50">
            <div class="full">
              <div class="service_img"> <img class="img-responsive" src="<?=App::config('url')?>public/images/news/<?=$nn->image?>" alt="#" /> </div>
              <div class="service_cont">
                <h3 class="service_head"><?=$nn->headline?></h3>
                <p><?=substr($news->text,0,75)?>...</p>
                <p>Author: <?php $id = News::findAuthor($news->id); echo $id;?></p>
                <p><?=$news->publishDate?></p>
                <div class="bt_cont"> <a class="btn sqaure_bt" href="<?=App::config('url')?>news/news_detail?id=<?=$nn->id?>">READ NEWS</a> </div>
              </div>
            </div>
          </div>
        <?php endforeach; ?>
        </div>
        <div class="row" style="margin-bottom: 30px;">
          <div class="col-md-12">
            <div class="full margin_bottom_30">
              <div class="accordion border_circle">
              </div>
            </div>
          </div>    
        </div>
        <div class="row">
        </div>
      </div>
      <div class="col-md-3">
        <div class="side_bar">
          <div class="side_bar_blog">
          <h4>SEARCH</h4>
            <div class="side_bar_search">
              <form action="<?=App::config('url')?>news/request_news">
              <div class="input-group stylish-input-group">
                <input class="form-control" name="search" value="<?=$search?>" placeholder="Search" type="text">
                <span class="input-group-addon">
                <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                </span> </div>
              </form>
            </div>
          </div>
          <div class="side_bar_blog">
          <h4><?=strtoupper($random->title)?></h4>
            <p><?=$random->smalldesc?></p>
            <a class="btn sqaure_bt" href="<?=App::config('url')?>services/service_detail?id=<?=$random->id?>">View Service</a></div>
            <div class="side_bar_blog">
            <h4>OUR SERVICE</h4>
            <div class="categary">
              <ul>
                <?php foreach($sideService as $sideService): ?>
                <li><a href="<?=App::config('url')?>services/service_detail?id=<?=$sideService->id?>"><i class="fa fa-angle-right"></i> <?=$sideService->title?></a></li>
                <?php endforeach;?>
              </ul>
            </div>
          </div>
          <div class="side_bar_blog">
            <h4>RECENT NEWS</h4>
            <div class="categary">
              <ul>
              <?php foreach($sideNews as $sideNews): ?>
                <li><a href="<?=App::config('url')?>news/news_detail?id=<?=$sideNews->id?>"><i class="fa fa-angle-right"></i> <?=$sideNews->headline?></a></li>
              <?php endforeach;?>
              </ul>
            </div>
          </div>
          <div class="side_bar_blog">
            <h4>TAG</h4>
            <div class="tags">
              <ul>
                <li><a href="#">Bootstrap</a></li>
                <li><a href="#">HTML5</a></li>
                <li><a href="#">Wordpress</a></li>
                <li><a href="#">Bootstrap</a></li>
                <li><a href="#">HTML5</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section padding_layout_1 testmonial_section white_fonts">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="main_heading text_align_left">
            <h2 style="text-transform: none;">What Clients Say?</h2>
            <p class="large">Here are testimonials from clients..</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-7">
        <div class="full">
          <div id="testimonial_slider" class="carousel slide" data-ride="carousel">
            <ul class="carousel-indicators">
              <li data-target="#testimonial_slider" data-slide-to="0" class="active"></li>
              <li data-target="#testimonial_slider" data-slide-to="1"></li>
              <li data-target="#testimonial_slider" data-slide-to="2"></li>
            </ul>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <div class="testimonial-container">
                  <div class="testimonial-content"> You guys rock! I was pleasantly surprised that they did the repair of my computer in a very short time. </div>
                  <div class="testimonial-photo"> <img src="<?=App::config('url')?>public/images/services/client1.jpg" class="img-responsive" alt="#" width="150" height="150"> </div>
                  <div class="testimonial-meta">
                    <h4>Elon Musk</h4>
                    <span class="testimonial-position">CEO of SpaceX</span> </div>
                </div>
              </div>
              <div class="carousel-item">
                <div class="testimonial-container">
                  <div class="testimonial-content">Thank you for making it painless, pleasant and most of all hassle free! I wish I would have thought of it first. 
                    I am really satisfied with my first laptop service. </div>
                  <div class="testimonial-photo"> <img src="<?=App::config('url')?>public/images/services/client2.jpg" class="img-responsive" alt="#" width="150" height="150"> </div>
                  <div class="testimonial-meta">
                    <h4>Jeff Bezos</h4>
                    <span class="testimonial-position">American entrepreneur</span> </div>
                </div>
              </div>
              <div class="carousel-item">
                <div class="testimonial-container">
                  <div class="testimonial-content"> You guys are great! Fast delivery of services. I ordered 50 games that arrived to me within 2 days, very fast delivery. Thank you guys a lot. </div>
                  <div class="testimonial-photo"> <img src="<?=App::config('url')?>public/images/services/client3.jpg" class="img-responsive" alt="#" width="150" height="150"> </div>
                  <div class="testimonial-meta">
                    <h4>Mate Rimac</h4>
                    <span class="testimonial-position">Croatian innovator</span> </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-5">
        <div class="full"> </div>
      </div>
    </div>
  </div>
</div>
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="contact_us_section">
            <div class="call_icon"> <img src="<?=App::config('url')?>public/images/services/phone_icon.png" alt="#" /> </div>
            <div class="inner_cont">
              <h2>REQUEST A FREE QUOTE</h2>
              <p>Get answers and advice from people you want it from.</p>
            </div>
            <div class="button_Section_cont"> <a class="btn dark_gray_bt" href="<?=App::config('url')?>index/contact">Contact us</a> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section padding_layout_1" style="padding: 50px 0;">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
      </div>
    </div>
  </div>
</div>