<footer class="footer_style_2">
  <div class="container-fuild">
    <div class="row">
      <div class="map_section">
        <div id="map"></div>
      </div>
      <div class="footer_blog">
        <div class="row">
          <div class="col-md-6">
            <div class="main-heading left_text">
              <h2>CyberX gaming shop</h2>
            </div>
            <p>CyberX was founded in 2018.</p>
            <ul class="social_icons">
              <li class="social-icon fb"><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li class="social-icon tw"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
              <li class="social-icon gp"><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
            </ul>
          </div>
          <div class="col-md-6">
            <div class="main-heading left_text">
              <h2>Additional links</h2>
            </div>
            <ul class="footer-menu">
              <li><a href="<?=App::config('url')?>index/about"><i class="fa fa-angle-right"></i> About us</a></li>
              <li><a href="<?=App::config('url')?>index/faq"><i class="fa fa-angle-right"></i> FAQ</a></li>
              <li><a href="<?=App::config('url')?>index/privacy_policy"><i class="fa fa-angle-right"></i> Privacy policy</a></li>
              <li><a href="<?=App::config('url')?>index/blog"><i class="fa fa-angle-right"></i> Blog</a></li>
              <li><a href="<?=App::config('url')?>index/contact><i class="fa fa-angle-right"></i> Contact us</a></li>
            </ul>
          </div>
          <div class="col-md-6">
            <div class="main-heading left_text">
              <h2>Services</h2>
            </div>
            <ul class="footer-menu">
            <?php $services = Service::sideBarServices();  ?>
            <?php if($services !=null): ?>
            <?php foreach($services as $service): ?>
              <li><a href="it_techn_support.html"><i class="fa fa-angle-right"></i> <?=$service->title?></a></li>
            <?php endforeach;?>
            <?php endif;?>
            </ul>
          </div>
          <div class="col-md-6">
            <div class="main-heading left_text">
              <h2>Contact us</h2>
            </div>
            <p>Pere Perića Street 1<br>
              31000,Osijek<br>
              <span style="font-size:18px;"><a href="tel:+9876543210">+987 654 3210</a></span></p>
            <div class="footer_mail-section">
              <form>
                <fieldset>
                <div class="field">
                  <input placeholder="Email" type="text">
                  <button class="button_custom"><i class="fa fa-envelope" aria-hidden="true"></i></button>
                </div>
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="cprt">
        <p>CyberX © Copyrights  <?php echo date('Y') ?></p>
      </div>
    </div>
  </div>
</footer>