<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title><?=App::config('appName')?></title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="initial-scale=1, maximum-scale=1">
<title><?=App::config('appName')?></title>
<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="<?=App::config('url')?>public/images/fevicon/fvcon.png" type="image/gif" />
<link rel="stylesheet" href="<?=App::config('url')?>public/css/bootstrap.min.css" />
<link rel="stylesheet" href="<?=App::config('url')?>public/css/style.css" />
<link rel="stylesheet" href="<?=App::config('url')?>public/css/responsive.css" />
<link rel="stylesheet" href="<?=App::config('url')?>public/css/colors1.css" />
<link rel="stylesheet" href="<?=App::config('url')?>public/css/custom.css" />
<link rel="stylesheet" href="<?=App::config('url')?>public/css/animate.css" />
<link rel="stylesheet" type="text/css" href="<?=App::config('url')?>public/revolution/css/settings.css" />
<link rel="stylesheet" type="text/css" href="<?=App::config('url')?>public/revolution/css/layers.css" />
<link rel="stylesheet" type="text/css" href="<?=App::config('url')?>public/revolution/css/navigation.css" />