<div class="bg_load"> <img class="loader_animation" src="<?=App::config('url')?>public/images/loaders/loader.png" alt="#" /> </div>
<header id="default_header" class="header_style_1">
  <div class="header_top">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div class="full">
            <div class="topbar-left">
              <ul class="list-inline">
                <li> <span class="topbar-label"><i class="fa  fa-home"></i></span> <span class="topbar-hightlight">Ulica Pere Perića 1, 31000 Osijek</span> </li>
                <li> <span class="topbar-label"><i class="fa fa-envelope-o"></i></span> <span class="topbar-hightlight"><a href="mailto:info@yourdomain.com">franko.vekic@gmail.com</a></span> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-4 right_section_header_top">
          <div class="float-left">
            <div class="social_icon">
              <ul class="list-inline">
              <li><a class="fa fa-facebook" href="https://www.facebook.com/franko.vekic" title="Facebook" target="_blank"></a></li>
                <li><a class="fa fa-instagram" href="https://www.instagram.com/franko.vekic" title="Instagram" target="_blank"></a></li>
                <li><a class="fa fa-github" href="https://github.com/FrankoVekic" title="Github" target="_blank"></a></li>
                <li><a class="fa fa-twitter" href="https://twitter.com" title="Twitter" target="_blank"></a></li>
                <li><a class="fa fa-linkedin" href="https://www.linkedin.com" title="LinkedIn" target="_blank"></a></li>
              </ul>
            </div>
          </div>
          <div class="float-right">
            <div class="make_appo"> <a class="btn white_btn" href="make_appointment.html">Make Appointment</a> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="header_bottom">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
          <div class="logo"> <a href="<?=App::config('url')?>index/home"><img src="<?=App::config('url')?>public/images/logos/it_logo.png" alt="logo" /></a> </div>
        </div>
        <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
          <div class="menu_side">
            <div id="navbar_menu">
              <ul class="first-ul">
                <li> <a class="active" href="<?=App::config('url')?>index/home">Home</a>
                </li>
                <li><a href="<?=App::config('url')?>index/about">About Us</a></li>
                <li> <a href="<?=App::config('url')?>index/service">Service</a>
                </li>
                <li> <a href="<?=App::config('url')?>index/blog">Blog</a>
                </li>
                <li> <a href="#">Pages</a>
                  <ul>
                    <li><a href="<?=App::config('url')?>index/career">Career</a></li>
                    <li><a href="<?=App::config('url')?>index/price">Pricing</a></li>
                    <li><a href="<?=App::config('url')?>index/faq">Faq</a></li>
                    <li><a href="<?=App::config('url')?>index/privacy_policy">Privacy Policy</a></li>
                  </ul>
                </li>
                <li> <a href="<?=App::config('url')?>products/shopping_cart">Shop</a>
                  <ul>
                    <li><a href="<?=App::config('url')?>products/equipment">Equipment</a></li>
                    <li><a href="<?=App::config('url')?>products/games">Games</a></li>
                    <li><a href="<?=App::config('url')?>products/shopping_cart">Shopping Cart</a></li>
                    <li><a href="<?=App::config('url')?>index/checkout">Checkout</a></li>
                  </ul>
                </li>
                <li> <a href="<?=App::config('url')?>index/contact">Contact</a>
                </li>
                <?php if(Request::isAdmin()):?>
                  <li> <a href="<?=App::config('url')?>index/organization">Manage</a>
                  <ul>
                  <li><a href="<?=App::config('url')?>manage/equipment">Manage Equipment</a></li>
                  <li><a href="<?=App::config('url')?>manage/games">Manage Games</a></li>
                  <li><a href="<?=App::config('url')?>manage/services">Manage Services</a></li>
                  </ul>
                </li>
                  <?php endif;?>
                <?php if(!Request::isAuthorized()): ?>
                <li> <a href="<?=App::config('url')?>index/login">Log In</a> </li>
                <?php else:?>
                  <li> <a href="<?=App::config('url')?>index/logout">Log Out</a> </li>
                <?php endif;?>
              </ul>
            </div>
            <div class="search_icon">
              <ul>
                <li><a href="#" data-toggle="modal" data-target="#search_bar"><i class="fa fa-search" aria-hidden="true"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>