<script src="<?=App::config('url')?>public/js/jquery.min.js"></script>
<script src="<?=App::config('url')?>public/js/bootstrap.min.js"></script>
<script src="<?=App::config('url')?>public/js/menumaker.js"></script>
<script src="<?=App::config('url')?>public/js/wow.js"></script>
<script src="<?=App::config('url')?>public/js/custom.js"></script>
<script src="<?=App::config('url')?>public/revolution/js/jquery.themepunch.tools.min.js"></script>
<script src="<?=App::config('url')?>public/revolution/js/jquery.themepunch.revolution.min.js"></script>
<script src="<?=App::config('url')?>public/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script src="<?=App::config('url')?>public/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
<script src="<?=App::config('url')?>public/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script src="<?=App::config('url')?>public/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script src="<?=App::config('url')?>public/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<script src="<?=App::config('url')?>public/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script src="<?=App::config('url')?>public/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script src="<?=App::config('url')?>public/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script src="<?=App::config('url')?>public/revolution/js/extensions/revolution.extension.video.min.js"></script>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<script>
         function initMap() {
           var map = new google.maps.Map(document.getElementById('map'), {
             zoom: 11,
             center: {lat: 40.645037, lng: -73.880224},
         styles: [
                  {
                    elementType: 'geometry',
                    stylers: [{color: '#fefefe'}]
                  },
                  {
                    elementType: 'labels.icon',
                    stylers: [{visibility: 'off'}]
                  },
                  {
                    elementType: 'labels.text.fill',
                    stylers: [{color: '#616161'}]
                  },
                  {
                    elementType: 'labels.text.stroke',
                    stylers: [{color: '#f5f5f5'}]
                  },
                  {
                    featureType: 'administrative.land_parcel',
                    elementType: 'labels.text.fill',
                    stylers: [{color: '#bdbdbd'}]
                  },
                  {
                    featureType: 'poi',
                    elementType: 'geometry',
                    stylers: [{color: '#eeeeee'}]
                  },
                  {
                    featureType: 'poi',
                    elementType: 'labels.text.fill',
                    stylers: [{color: '#757575'}]
                  },
                  {
                    featureType: 'poi.park',
                    elementType: 'geometry',
                    stylers: [{color: '#e5e5e5'}]
                  },
                  {
                    featureType: 'poi.park',
                    elementType: 'labels.text.fill',
                    stylers: [{color: '#9e9e9e'}]
                  },
                  {
                    featureType: 'road',
                    elementType: 'geometry',
                    stylers: [{color: '#eee'}]
                  },
                  {
                    featureType: 'road.arterial',
                    elementType: 'labels.text.fill',
                    stylers: [{color: '#3d3523'}]
                  },
                  {
                    featureType: 'road.highway',
                    elementType: 'geometry',
                    stylers: [{color: '#eee'}]
                  },
                  {
                    featureType: 'road.highway',
                    elementType: 'labels.text.fill',
                    stylers: [{color: '#616161'}]
                  },
                  {
                    featureType: 'road.local',
                    elementType: 'labels.text.fill',
                    stylers: [{color: '#9e9e9e'}]
                  },
                  {
                    featureType: 'transit.line',
                    elementType: 'geometry',
                    stylers: [{color: '#e5e5e5'}]
                  },
                  {
                    featureType: 'transit.station',
                    elementType: 'geometry',
                    stylers: [{color: '#000'}]
                  },
                  {
                    featureType: 'water',
                    elementType: 'geometry',
                    stylers: [{color: '#c8d7d4'}]
                  },
                  {
                    featureType: 'water',
                    elementType: 'labels.text.fill',
                    stylers: [{color: '#b1a481'}]
                  }
                ]
         });
         
           var image = "<?=App::config('url')?>public/images/it_service/location_icon_map_cont.png";
           var beachMarker = new google.maps.Marker({
             position: {lat: 40.645037, lng: -73.880224},
             map: map,
             icon: image
           });
         }
      </script>
      <script src='<?=App::config('url')?>public/js/hizoom.js'></script>
<script>
        $('.hi1').hiZoom({
            width: 300,
            position: 'right'
        });
        $('.hi2').hiZoom({
            width: 400,
            position: 'right'
        });
    </script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>