<div class="center">
<nav aria-label="...">
  <ul class="pagination justify-content-center">
    <?php if($page!=1 && $pageCount<=3): ?>
      <li class="page-item">
      <a class="page-link" href="<?=App::config('url')?>manage/<?=ManageController::checkSearchService()?>?page=<?php echo $page-1?><?php if(!empty($search)){echo '&search=' . $search;}?>" tabindex="-1"><</a>
    </li>
    <li class="page-item"><a class="page-link" href="<?=App::config('url')?>manage/<?=ManageController::checkSearchService()?>?page=<?php echo $page-1?><?php if(!empty($search)){echo '&search=' . $search;}?>"><?=$page-1?></a></li>
    <?php elseif($pageCount>3 && $page > 2): ?>
      <li class="page-item">
      <a class="page-link" href="<?=App::config('url')?>manage/<?=ManageController::checkSearchService()?>?page=1" tabindex="-1"><<</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="<?=App::config('url')?>manage/<?=ManageController::checkSearchService()?>?page=<?php echo $page-1?><?php if(!empty($search)){echo '&search=' . $search;}?>" tabindex="-1"><</a>
    </li>
    <li class="page-item"><a class="page-link" href="<?=App::config('url')?>manage/<?=ManageController::checkSearchService()?>?page=<?php echo $page-1?><?php if(!empty($search)){echo '&search=' . $search;}?>"><?=$page-1?></a></li>
    <?php elseif($page!=1): ?>
      <li class="page-item">
      <a class="page-link" href="<?=App::config('url')?>manage/<?=ManageController::checkSearchService()?>?page=<?php echo $page-1?><?php if(!empty($search)){echo '&search=' . $search;}?>" tabindex="-1"><</a>
    </li>
    <li class="page-item"><a class="page-link" href="<?=App::config('url')?>manage/<?=ManageController::checkSearchService()?>?page=<?php echo $page-1?><?php if(!empty($search)){echo '&search=' . $search;}?>"><?=$page-1?></a></li>
    <?php else : ?>
      <li class="page-item"><a class="page-link"><</a></li>
    <?php endif; ?>
    <li class="page-item active">
      <a class="page-link" href="<?=App::config('url')?>manage/<?=ManageController::checkSearchService()?>?page=<?=$page?><?php if(!empty($search)){echo '&search=' . $search;}?>"><?=$page?> <span class="sr-only"></span></a>
    </li>
    <?php if($page != $pageCount && $pageCount>3): ?>
    <li class="page-item"><a class="page-link" href="<?=App::config('url')?>manage/<?=ManageController::checkSearchService()?>?page=<?php echo $page+1?>"><?=$page+1?><?php if(!empty($search)){echo '&search=' . $search;}?></a></li>
    <li class="page-item">
      <a class="page-link" href="<?=App::config('url')?>manage/<?=ManageController::checkSearchService()?>?page=<?php echo $page+1?><?php if(!empty($search)){echo '&search=' . $search;}?>">></a>
    </li>
    <li class="page-item">
      <a class="page-link" href="<?=App::config('url')?>manage/<?=ManageController::checkSearchService()?>?page=<?php echo $pageCount?><?php if(!empty($search)){echo '&search=' . $search;}?>">>></a>
    </li>
    <?php elseif($page != $pageCount && $pageCount<=3):?>
      <li class="page-item"><a class="page-link" href="<?=App::config('url')?>manage/<?=ManageController::checkSearchService()?>?page=<?php echo $page+1?><?php if(!empty($search)){echo '&search=' . $search;}?>"><?=$page+1?></a></li>
    <li class="page-item">
      <a class="page-link" href="<?=App::config('url')?>manage/<?=ManageController::checkSearchService()?>?page=<?php echo $page+1?><?php if(!empty($search)){echo '&search=' . $search;}?>">></a>
    </li>
    <?php else : ?>
      <li class="page-item"><a class="page-link">></a></li>
    <?php endif; ?>
  </ul>
 </nav>
</div>