<div id="inner_banner" class="section inner_banner_section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="title-holder">
            <div class="title-holder-cell text-left">
              <h1 class="page-title">Manage Service</h1>
              <ol class="breadcrumb">
                <li><a href="<?=App::config('url')?>index/home">Home</a></li>
                <li class="active">Manage Service</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section padding_layout_1 service_list">
  <div class="container">
    <div class="row">
    <div class="side_bar_blog">
        <h3 style="text-align:center;">FIND SERVICE</h3>
          <div class="side_bar_search">
            <form action="<?=App::config('url')?>manage/request_service">
              <div class="input-group stylish-input-group">
                  <input class="form-control" name="search" value="<?=$search?>" placeholder="Search" type="text">
                  <span class="input-group-addon">
                <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
              </span> </div>
          </form>
        </div>
    </div>
    <?php if($service != null && Service::serviceCount() >=3): ?>
      <div class="center">
        <a href="<?=App::config('url')?>manage/new_service" class="btn main_bt" type="submit">Add New</a>
    </div>
    <?php endif;?>
    <div class="container">
    <div class="col-md-4">
         <h3><?=$message?></h3>
     </div>
    <div class="row">
      <?php if($service != null): ?>
        <?php foreach($service as $ser): ?>
      <div class="col-md-4 service_blog margin_bottom_50">
        <div class="full">
          <div class="service_img"> <img class="img-responsive" src="<?=App::config('url')?>public/images/services/<?=$ser->image?>" alt="#" /> </div>
          <div class="service_cont">
            <h3 class="service_head"><?=$ser->title?></h3>
            <p><?=$ser->smalldesc?></p>
            <div class="bt_cont"> <a style="margin-right:5px;" class="btn sqaure_bt" href="<?=App::config('url')?>manage/edit_service?service=<?=$ser->title?>">Edit</a><a onclick="return confirm('Are you sure you want to delete &#34;<?=$ser->title?>&#34; from the store?');" class="btn sqaure_bt" style="background-color:indianred" href="<?=App::config('url')?>manage/delete?game=<?=$ser->title?>">Delete</a> </div>
          </div>
        </div>
      </div>
     <?php endforeach;?>
     <?php if(Service::serviceCount()<=2): ?>
    <div class="col-md-4 service_blog margin_bottom_50">
        <div class="full">
          <div class="service_img"> <img class="img-responsive" src="/public/images/shop/newService.jpg" alt="#" /> </div>
          <div class="service_cont">
            <h3 class="service_head">Add New Service</h3>
            <p>Add a service. You must fill in the appropriate information in order to enter the service to the shop.</p>
            <div class="bt_cont"> <a style="margin-right:5px; background-color:seagreen" class="btn sqaure_bt btn-lg btn-block" href="new_service">Add</a> </div>
          </div>
        </div>
      </div>;
      <?php endif;?>
    </div>
    <?php include 'pagingSer.phtml'; ?>
    <?php else: ?>
      <?php if(isset($newService)){echo $newService;}?>
      <?php if(isset($backButton)){echo $backButton;} ?>
    <?php endif;?>
  </div>
</div>
    </div>
</div>
</div>
<div class="section padding_layout_1 testmonial_section white_fonts">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="main_heading text_align_left">
            <h2 style="text-transform: none;">What Clients Say?</h2>
            <p class="large">Here are testimonials from clients..</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-7">
        <div class="full">
          <div id="testimonial_slider" class="carousel slide" data-ride="carousel">
            <ul class="carousel-indicators">
              <li data-target="#testimonial_slider" data-slide-to="0" class="active"></li>
              <li data-target="#testimonial_slider" data-slide-to="1"></li>
              <li data-target="#testimonial_slider" data-slide-to="2"></li>
            </ul>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <div class="testimonial-container">
                  <div class="testimonial-content"> You guys rock! I was pleasantly surprised that they did the repair of my computer in a very short time. </div>
                  <div class="testimonial-photo"> <img src="<?=App::config('url')?>public/images/services/client1.jpg" class="img-responsive" alt="#" width="150" height="150"> </div>
                  <div class="testimonial-meta">
                    <h4>Elon Musk</h4>
                    <span class="testimonial-position">CEO of SpaceX</span> </div>
                </div>
              </div>
              <div class="carousel-item">
                <div class="testimonial-container">
                  <div class="testimonial-content">Thank you for making it painless, pleasant and most of all hassle free! I wish I would have thought of it first. 
                    I am really satisfied with my first laptop service. </div>
                  <div class="testimonial-photo"> <img src="<?=App::config('url')?>public/images/services/client2.jpg" class="img-responsive" alt="#" width="150" height="150"> </div>
                  <div class="testimonial-meta">
                    <h4>Jeff Bezos</h4>
                    <span class="testimonial-position">American entrepreneur</span> </div>
                </div>
              </div>
              <div class="carousel-item">
                <div class="testimonial-container">
                  <div class="testimonial-content"> You guys are great! Fast delivery of services. I ordered 50 games that arrived to me within 2 days, very fast delivery. Thank you guys a lot. </div>
                  <div class="testimonial-photo"> <img src="<?=App::config('url')?>public/images/services/client3.jpg" class="img-responsive" alt="#" width="150" height="150"> </div>
                  <div class="testimonial-meta">
                    <h4>Mate Rimac</h4>
                    <span class="testimonial-position">Croatian innovator</span> </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-5">
        <div class="full"> </div>
      </div>
    </div>
  </div>
</div>
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="contact_us_section">
            <div class="call_icon"> <img src="<?=App::config('url')?>public/images/services/phone_icon.png" alt="#" /> </div>
            <div class="inner_cont">
              <h2>REQUEST A FREE QUOTE</h2>
              <p>Get answers and advice from people you want it from.</p>
            </div>
            <div class="button_Section_cont"> <a class="btn dark_gray_bt" href="<?=App::config('url')?>index/contact">Contact us</a> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section padding_layout_1" style="padding: 50px 0;">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
      </div>
    </div>
  </div>
</div>